name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --no-interaction --prefer-dist

      # - name: Run DashboardControllerTest
      #   env:
      #     APP_ENV: test
      #     DATABASE_URL: "mysql://root:root@127.0.0.1:3306/safebase?serverVersion=8.0.32&charset=utf8mb4"
      #   run: php bin/phpunit

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/ci-cd-pipeline .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ci-cd-pipeline
